import 'dart:async';
import 'dart:convert';
import 'dart:io';

/// The self-signed loopback HTTPS endpoint the per-source TLS-confirmation rows
/// drive (#75), on the host and on a handset alike.
///
/// `test/fixtures/tls/localhost.{crt,key}` are the fixture pair — a self-signed
/// leaf no client trusts, generated by the commands in that directory's
/// `README.md` — but an instrumented test runs on a device that has no checkout,
/// so the pair travels in the program as the DER each PEM wraps. That is the
/// shape the WebView oracle already uses for its own certificates
/// (`tool/webview_oracle/fixture.json` carries `certificateDerBase64` and
/// `privateKeyPkcs8Base64`), and `tls_localhost_fixture_test.dart` pins both
/// constants against the committed files so the copy cannot drift.
const String localhostCertificateDer =
    'MIIDJzCCAg+gAwIBAgIUOCA/0a61YoH+3TMJQXYjmZuku70wDQYJKoZIhvcNAQELBQAwFDESMBAG'
    'A1UEAwwJbG9jYWxob3N0MCAXDTI2MDkxNzA5MTYxM1oYDzIxMjYwODI0MDkxNjEzWjAUMRIwEAYD'
    'VQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlIq+j24T/yVnz'
    'bL6jrBGH1X3s6yETK/v6OPHvm1uyqj/iS5e4WKp5BWzFoJXl23QsWM8OXmYqqH2WA6tveUE543h6'
    'GtkJ1UO1hwQVhyQB6QYoV0zxtRzGParCBT0kSxLih0VLj+dPSuKru5eL79a10/LF/a9yEc3sxu56'
    'gyDK/QixqE0XK5qEbzP5/dCZFtXxviI/nllpqh5AuKEr0dMPF2zcEMcHb6SJME1uyuLLfJIR5KSE'
    '0xFPSXhCz7sOL5WeSxXIUYegcTzPJ9xTV1WVBXexfavTqY6J/WVDIXX3hx3qX4vVOZaQCQL7Paxv'
    'p9sFnFPGW6PyZ/DUidRozT/HAgMBAAGjbzBtMB0GA1UdDgQWBBQeCJgqkA1z+//30MA5kudKpQpI'
    'BTAfBgNVHSMEGDAWgBQeCJgqkA1z+//30MA5kudKpQpIBTAPBgNVHRMBAf8EBTADAQH/MBoGA1Ud'
    'EQQTMBGCCWxvY2FsaG9zdIcEfwAAATANBgkqhkiG9w0BAQsFAAOCAQEAOgMH3lAcmvhAgBPoWUJe'
    'MszL5UzeY+Ev9i3KaNLaAovxTQNgZRUB4SL16E03uOaOatvxD7sdLs8yRl1R/CpA30clwVTDMqaK'
    'qIYteKkNYxYwnVOMBHjmFZ7rsd75J7bzwnM9pMbgJxb3f1iHMPi9ycHyw5M4OvmMExRCJVP0cnx6'
    'lRAsgSFUKdVfOLtCPVjE8IQDfuQssR97DdgIVJgZ0h4nGTr99kqmIatqeLF/NQSgTVASWJsQlZ5z'
    '/pYeLU2NKo/zNzo6mVIY1L+TBM1AREVU7giKrxZgx5cwnkC0bn3rGrWHP3upbcwHArrMKTl32BSi'
    'l6vKadA/syP1o9qYHg==';

const String localhostPrivateKeyDer =
    'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDlIq+j24T/yVnzbL6jrBGH1X3s'
    '6yETK/v6OPHvm1uyqj/iS5e4WKp5BWzFoJXl23QsWM8OXmYqqH2WA6tveUE543h6GtkJ1UO1hwQV'
    'hyQB6QYoV0zxtRzGParCBT0kSxLih0VLj+dPSuKru5eL79a10/LF/a9yEc3sxu56gyDK/QixqE0X'
    'K5qEbzP5/dCZFtXxviI/nllpqh5AuKEr0dMPF2zcEMcHb6SJME1uyuLLfJIR5KSE0xFPSXhCz7sO'
    'L5WeSxXIUYegcTzPJ9xTV1WVBXexfavTqY6J/WVDIXX3hx3qX4vVOZaQCQL7Paxvp9sFnFPGW6Py'
    'Z/DUidRozT/HAgMBAAECggEAbnojYmdQwH1mI+KuJj8r8qjCfu09dL9zzgkPyX3IICRLCgJ1hBoo'
    'E5LEh6LuMzX01P760kw8iVvUtXROf8BgbRdaetEgDUgozcjr9K9EcrFWWTQCctXmqkSIZOTevnV+'
    'BP/ArvaSyd3q3W9k2cFJbkDjYIf4xBCGj5+40xQPRx8AhOJWWf/iMk4EWcQ5BGvRnG3q+wbC9MCc'
    'UKzZK/4fu4lr5C7S/1RzoSa6FmRlgk8CjRkr8fBy36xOD81/eWVwpZwVcj8gWstFGRk1jWTVIqwr'
    '+1z//fFIi1Rcxz/AcEdy9w5xQN00AY5eSysbYS2V8cDzLc+uLnLrE4a15U4R1QKBgQD8kFA0LdWK'
    'ZT5qbG6LqwT3Mpff0CteNf9hI2xTydXl1zBxciDcsEwQool/g9lypAcyiTrI3Q5XmhHubPDgpFIp'
    'oVyQ1R2/IHAWaTq2vruJ9e/WCbGT87cjHH4UAOpah2EeFMgIpqEqgP83Emjh9zQce+EubuxgkqXF'
    'hNsC67RwVQKBgQDoQMWHSBVEuGQcKcd0uXeU/s7Uzu3fDGjspxHAvUiCfGV8Yx83JZb2NrN7RI47'
    '9BskZiYPXgYn5sgJnSFQFS/qofLEqKFK2ieTtfKqts57rrGitmJojS6r9eOuBpQqTvPs1PXuPBfV'
    'cWKdutOpC3stMyMs95XLcLK+Ufkr/fhbqwKBgQDYwS3kKjXrKYrQoTCac3K2iFgpgCnIGAWNo24T'
    '1tPZBr6Pjkg/vpn5aNUid9DF/5oht/6YZocpjZO4EQ0FbmEJU2/y6MQ3xKoNwc/fCIBBHa3w/q7F'
    'cFOLMafOmR6IBUnHHES0j/UfWkguRoF29MZnb7XJOO9qzlCw3J1tu0ZHZQKBgQDBNeEdgaHv4VWm'
    '+Dqtp/0LPk7iSqMogzJmbTYfmVfQ9ZuXtv4o6mSDv03gpk+NIK3Twga3kgic+ShAly83Z+jM0J0d'
    'bQuBMarq/to5mop76gBs1D1ZrNm+xHf8NgzchYH269MLtYI+Vm0ruliKsLpwB7KjnfRHoiGQorEf'
    'H9CUsQKBgBm3Q8ETNTE4ZU+tt8HgJNB9SDBJw/sRVteVrWAYpnXjjqZKSriLDkp8grfNjLwj2Fwg'
    'jJErENyZN9bFkDjdkx1CQb4yh8S6BRcqv7flIsZWLXCfSCzcCnBSRO2Q7TWa+lheI2MCXce1hfmf'
    'yF57DJSXKLqBk/Vlp9C8yXigEBzR';

/// A PEM document around [base64Body], which is what a [SecurityContext] reads.
String _pem(String label, String base64Body) {
  final lines = <String>['-----BEGIN $label-----'];
  for (var offset = 0; offset < base64Body.length; offset += 64) {
    final end = offset + 64 > base64Body.length
        ? base64Body.length
        : offset + 64;
    lines.add(base64Body.substring(offset, end));
  }
  lines.add('-----END $label-----');
  return '${lines.join('\n')}\n';
}

/// One loopback HTTPS endpoint serving [pageText] under the fixture
/// certificate, with what it observed.
///
/// The listener is a plain [ServerSocket] whose connections are upgraded one at
/// a time, rather than a `SecureServerSocket`, because dart:io surfaces a
/// connection only after its handshake succeeds: a client that refuses the
/// certificate — the WebView's state before the user confirms, and the refusal
/// row's whole point — would otherwise be indistinguishable from one that never
/// connected. [connectionsAccepted] therefore counts raw connections, so a
/// refusal is still an observation. The WebView oracle's own replay server makes
/// the same distinction for the same reason (`replay_server.dart`, "a client
/// that refuses the fixture's certificate aborts the handshake, so the fixture
/// would otherwise observe nothing at all").
class TlsLocalhostFixtureServer {
  TlsLocalhostFixtureServer._(this._listener, this._context, this.pageText);

  /// Binds the endpoint on the loopback interface and serves one page.
  static Future<TlsLocalhostFixtureServer> bind({
    required String pageText,
  }) async {
    final context = SecurityContext(withTrustedRoots: false)
      ..useCertificateChainBytes(
        utf8.encode(_pem('CERTIFICATE', localhostCertificateDer)),
      )
      ..usePrivateKeyBytes(
        utf8.encode(_pem('PRIVATE KEY', localhostPrivateKeyDer)),
      );
    final listener = await ServerSocket.bind(InternetAddress.loopbackIPv4, 0);
    final server = TlsLocalhostFixtureServer._(listener, context, pageText);
    server._accept();
    return server;
  }

  /// The document text the page carries, so a caller asserts on one spelling.
  final String pageText;

  final ServerSocket _listener;
  final SecurityContext _context;
  final Set<Socket> _open = {};
  final List<Future<void>> _serving = [];

  /// Raw connections the listener accepted, counted before the handshake decides
  /// anything.
  int connectionsAccepted = 0;

  /// Requests for [url] that arrived over a completed handshake.
  int pageRequests = 0;

  /// The endpoint's own authority, as a source's identity URL spells it.
  String get authority => '127.0.0.1:$port';

  /// The port the endpoint bound.
  int get port => _listener.port;

  /// The page: the origin a WebView has to reach through the certificate the
  /// client does not trust.
  String get url => 'https://$authority/page';

  /// What this endpoint observed, for a row's evidence line.
  Map<String, Object?> get observation => {
    'connectionsAccepted': connectionsAccepted,
    'pageRequests': pageRequests,
  };

  void _accept() {
    _listener.listen(
      (connection) {
        connectionsAccepted++;
        _open.add(connection);
        final serving = _serve(connection)
            .catchError((Object _) {})
            .whenComplete(() => _open.remove(connection));
        _serving.add(serving);
      },
      onError: (Object _) {},
      cancelOnError: false,
    );
  }

  Future<void> _serve(Socket raw) async {
    final Socket secure;
    try {
      secure = await SecureSocket.secureServer(raw, _context);
    } on TlsException {
      // The client refused the certificate: that is the observation this server
      // exists to make, not a fault.
      return;
    }
    try {
      final head = await _requestHead(secure);
      if (head != null && head.startsWith('GET /page ')) pageRequests++;
      final body = utf8.encode(
        '<!doctype html><html><body><p>$pageText</p></body></html>',
      );
      secure.add(
        utf8.encode(
          'HTTP/1.1 200 OK\r\n'
          'Content-Type: text/html; charset=utf-8\r\n'
          'Content-Length: ${body.length}\r\n'
          'Connection: close\r\n\r\n',
        ),
      );
      secure.add(body);
      await secure.flush();
    } on SocketException {
      // A client can disconnect while the response is being written; that is an
      // expected observation, not a server failure.
    } finally {
      await secure.close();
    }
  }

  /// The request head, once the client has sent it; null when the connection
  /// ended first.
  static Future<String?> _requestHead(Socket socket) {
    final buffer = <int>[];
    final completer = Completer<String?>();
    socket.listen(
      (chunk) {
        if (completer.isCompleted) return;
        buffer.addAll(chunk);
        for (var index = 0; index + 3 < buffer.length; index++) {
          if (buffer[index] == 13 &&
              buffer[index + 1] == 10 &&
              buffer[index + 2] == 13 &&
              buffer[index + 3] == 10) {
            completer.complete(latin1.decode(buffer.sublist(0, index)));
            return;
          }
        }
      },
      onError: (Object _) {
        if (!completer.isCompleted) completer.complete(null);
      },
      onDone: () {
        if (!completer.isCompleted) completer.complete(null);
      },
      cancelOnError: false,
    );
    return completer.future;
  }

  /// Closes the listener and drops the connections still open.
  ///
  /// A WebView keeps idle sockets open, and a handler for such a socket never
  /// finishes on its own because no request arrives on it; observations are
  /// already recorded by then, so dropping them loses no evidence.
  Future<void> close() async {
    await _listener.close();
    for (final connection in _open.toList()) {
      connection.destroy();
    }
    await Future.wait(_serving.toList())
        .timeout(const Duration(seconds: 2), onTimeout: () => <void>[])
        .catchError((Object _) => <void>[]);
  }
}
