// The frozen `io.legado.app.utils` members `AnalyzeRule.kt` names, for the
// compile classpath only.
//
// The files that declare them (`MapExtensions.kt`, `StringExtensions.kt`,
// `GsonExtensions.kt`, `LogUtils.kt`) mix them with Android, hutool and OkHttp
// members, so the small ones `AnalyzeRule.kt` reaches are transcribed here and
// `HtmlContentOracle` fails the run unless the frozen file still contains each
// transcription (whitespace-normalised):
//
// - `getOrPutLimit` (`MapExtensions.kt:21-33`) — the rule and regex caches;
// - `isJson` (`StringExtensions.kt:46-55`) — `setContent`'s `isJSON` flag,
//   which decides whether a bare rule is read as JSON;
// - `splitNotBlank` (`StringExtensions.kt:81-84`) — the `&&` form of
//   `getElement`/`getElements`, which this corpus never calls;
// - `printOnDebug` (`LogUtils.kt:139-143`) — gated on `BuildConfig.DEBUG`, which
//   the Android build generates; the stub is the release behaviour and is
//   quoted, not transcribed, because the frozen statement is the `DEBUG` gate;
// - `stackTraceStr` (`ThrowableExtensions.kt:5-13`) — the `ajax` failure text.
//
// `fromJsonObject` and `GSON` are named by `splitPutRule`'s `@put:` branch, which
// no corpus case declares; that path is not exercised here, and no corpus row
// may claim it.
package io.legado.app.utils

import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

/** The frozen `GSON` (`GsonExtensions.kt:41`). The frozen builder registers
 * serializers this corpus does not exercise: `GSON` is named by `splitPutRule`'s
 * unreached `@put:` branch only. */
val GSON: Gson = Gson()

/** `GsonExtensions.kt:54-58`, as far as a desktop JVM needs it: `@put:` values
 * are not reached by this corpus. */
inline fun <reified T> Gson.fromJsonObject(json: String?): Result<T> =
    runCatching { fromJson(json, TypeToken.get(T::class.java).type) }

/** `MapExtensions.kt:21-33`, transcribed. */
inline fun <K, V> MutableMap<K, V>.getOrPutLimit(key: K, maxSize: Int, defaultValue: () -> V): V {
    var value = get(key)
    if (containsKey(key)) {
        @Suppress("UNCHECKED_CAST")
        return value as V
    }
    value = defaultValue()
    if (size < maxSize) {
        put(key, value)
    }
    return value
}

/** `StringExtensions.kt:46-55`, transcribed. */
fun String?.isJson(): Boolean =
    this?.run {
        val str = this.trim()
        when {
            str.startsWith("{") && str.endsWith("}") -> true
            str.startsWith("[") && str.endsWith("]") -> true
            else -> false
        }
    } ?: false

/** `StringExtensions.kt:81-84`, transcribed. */
fun String.splitNotBlank(vararg delimiter: String, limit: Int = 0): Array<String> = run {
    this.split(*delimiter, limit = limit).map { it.trim() }.filterNot { it.isBlank() }
        .toTypedArray()
}

// The frozen `Throwable.printOnDebug` lives in `LogUtils.kt:139-143` as
//
//     fun Throwable.printOnDebug() {
//         if (BuildConfig.DEBUG) printStackTrace()
//     }
//
// and `BuildConfig` is generated by the Android build. The release behaviour is
// supplied, exactly as `tool/tonum_chapter_oracle/FrozenDebugStub.kt` does it:
// stack traces and debug logs are not compatibility surfaces.

/** The frozen `printOnDebug` under `BuildConfig.DEBUG = false`: no output. */
fun Throwable.printOnDebug() = Unit

/** `ThrowableExtensions.kt:5-13`, transcribed. */
val Throwable.stackTraceStr: String
    get() {
        val stackTrace = stackTraceToString()
        val lMsg = this.localizedMessage ?: "noErrorMsg"
        return when {
            stackTrace.isNotEmpty() -> stackTrace
            else -> lMsg
        }
    }
