import 'dart:io';

/// Writes `lib/source/public_suffix_list.dart` from a snapshot of
/// <https://publicsuffix.org/list/public_suffix_list.dat>:
///
/// ```
/// dart run tool/generate_public_suffix_list.dart <path to public_suffix_list.dat>
/// ```
///
/// The list itself asks to be pulled only from that URL, so the snapshot is
/// fetched by hand and handed to this tool. The generated file carries the
/// list's own `VERSION` and `COMMIT` lines: which list a build keys cookies
/// with is then a recorded fact instead of a moving target, and a refresh is a
/// regenerated file with a new header, reviewed like any other change.
Future<void> main(List<String> args) async {
  if (args.length != 1) {
    stderr.writeln(
      'usage: dart run tool/generate_public_suffix_list.dart '
      '<path to public_suffix_list.dat>',
    );
    exitCode = 2;
    return;
  }
  final source = File(args.single);
  if (!await source.exists()) {
    stderr.writeln('no such file: ${source.path}');
    exitCode = 2;
    return;
  }
  final lines = await source.readAsLines();
  final rules = <String>[];
  String? version;
  String? commit;
  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.startsWith('//')) {
      // Only the section markers survive: the parser that reads this list back
      // needs them to tell the ICANN rules from the private ones, and the
      // provenance lines become fields of their own.
      if (trimmed.contains('BEGIN ICANN') ||
          trimmed.contains('END ICANN') ||
          trimmed.contains('BEGIN PRIVATE') ||
          trimmed.contains('END PRIVATE')) {
        rules.add(trimmed);
      }
      if (trimmed.startsWith('// VERSION:')) {
        version = trimmed.substring('// VERSION:'.length).trim();
      }
      if (trimmed.startsWith('// COMMIT:')) {
        commit = trimmed.substring('// COMMIT:'.length).trim();
      }
      continue;
    }
    if (trimmed.isEmpty) continue;
    // publicsuffix.org defines a rule as the part of the line before the first
    // whitespace; the rest is commentary.
    rules.add(trimmed.split(' ').first);
  }
  if (version == null || commit == null) {
    stderr.writeln('the snapshot has no VERSION/COMMIT header lines');
    exitCode = 1;
    return;
  }
  if (rules.any((rule) => rule.contains("'''"))) {
    throw StateError('the list contains a triple quote the raw string cannot hold');
  }
  final header = File('lib/source/public_suffix_list.dart');
  await header.writeAsString('''
// GENERATED by tool/generate_public_suffix_list.dart — do not hand-edit.
//
// Data: https://publicsuffix.org/list/public_suffix_list.dat
// VERSION: $version
// COMMIT: $commit
//
// The list is data under the Mozilla Public License 2.0
// (https://mozilla.org/MPL/2.0/); it is embedded as text so that the cookie
// key derivation is the same in the app, in `flutter test`, and in a
// `dart run tool/…` gate, with no asset bundle to load.

/// The public suffix list snapshot this build keys cookies with.
const publicSuffixListVersion = '$version';

/// The list's own commit, from the same header.
const publicSuffixListCommit = '$commit';

/// The rules, in the list's own order, with its provenance comments removed.
const publicSuffixList = r\'\'\'
${rules.join('\n')}
\'\'\';
''');
  stdout.writeln(
    'wrote ${header.path}: ${rules.length} lines, VERSION $version, '
    'COMMIT $commit',
  );
}
