"""Build the crate's conversion fixture from the measured baseline oracle.

Usage:
  python tool/text_engine_prototype/make_conversion_fixture.py <oracle-dir> <probe-dir>

Reads the oracle JSONL (`BaselineOracle` output, one record per line) and the
probe's per-line dump (`conversion_probe ... --dump`), and writes
`packages/fjs/liber_text/assets/conversion_fixtures.tsv`: one row per input,
with the direction, the input, what this product's tables produce, what the
frozen baseline produces, and `divergence` when the two differ.

The fixture is what `cargo test` asserts, so a table or matcher change that
moves the output fails the test instead of silently shipping. Regenerating it is
a deliberate step: run the pipeline (README.md), regenerate, and read the diff —
new `divergence` rows are new divergences from the frozen reader.

Arguments: the directory holding `probes.jsonl`, `probes-s2t.jsonl` and
`probes-dump.jsonl`, `probes-s2t-dump.jsonl`.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FIXTURE = ROOT / 'packages/fjs/liber_text/assets/conversion_fixtures.tsv'
PROBE_T2S = 'liber-reading:t2s'
PROBE_S2T = 'hanlp-fmm:s2t'
HEADER = """# Chinese conversion fixtures for packages/fjs/liber_text.
#
# Generated by tool/text_engine_prototype/make_conversion_fixture.py from the
# frozen baseline oracle (quick-transfer-core 0.2.16 plus Legado's fixT2sDict
# exclude list, tool/text_engine_prototype/BaselineOracle.java) and this
# crate's tables (HanLP 1.x data/dictionary/tc, Apache-2.0).
#
# direction<TAB>input<TAB>this product<TAB>frozen baseline<TAB>note
#
# An empty note means the two agree; `divergence` means they do not. The product
# column is this crate's reading conversion (`convert_to(..., SimplifiedMainland)`:
# characters plus regional wording), the baseline column is the frozen reader.
# Every `divergence` row records a deliberate difference, not a defect: the
# frozen table turns Taiwan words into mainland ones and keeps a mainland reader's
# words (存檔 -> 存盘) where this product follows the mainland reference (-> 存档),
# and it keeps a character this product converts (乾).
"""


def load_jsonl(path):
    return [json.loads(line) for line in path.read_text(encoding='utf-8').splitlines()]


def field(value, label):
    if '\t' in value or '\n' in value:
        raise SystemExit(f'{label} contains a tab or newline: {value!r}')
    return value


def rows_from(oracle, dump, direction, probe_key):
    dumps = {record['i']: record for record in load_jsonl(dump)}
    rows = []
    for record in load_jsonl(oracle):
        source = field(record['src'], 'input')
        product = field(dumps[record['i']][probe_key], 'product output')
        baseline = field(record['t2s' if direction == 't2s' else 's2t'], 'baseline output')
        note = '' if product == baseline else 'divergence'
        rows.append((direction, source, product, baseline, note))
    return rows


def exclude_rows():
    """The exclude list itself, one row per word, straight from the crate."""
    words = []
    source = (ROOT / 'packages/fjs/liber_text/src/convert.rs').read_text(encoding='utf-8')
    body = source.split('pub const T2S_EXCLUDE: &[&str] = &[', 1)[1].split('];', 1)[0]
    for raw in body.split(','):
        word = raw.strip().strip('"')
        if word:
            words.append(word)
    return [('t2s', word, word, word, '') for word in words]


def main():
    oracle_dir = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'D:/liber-probe/text-engine')
    rows = []
    rows += rows_from(oracle_dir / 'probes.jsonl', oracle_dir / 'probes-dump.jsonl',
                      't2s', PROBE_T2S)
    rows += rows_from(oracle_dir / 'probes-s2t.jsonl', oracle_dir / 'probes-s2t-dump.jsonl',
                      's2t', PROBE_S2T)
    rows += exclude_rows()
    lines = [HEADER]
    for row in rows:
        lines.append('\t'.join(row) + '\n')
    FIXTURE.write_text(''.join(lines), encoding='utf-8', newline='\n')
    divergences = sum(1 for row in rows if row[4])
    print(f'{FIXTURE.relative_to(ROOT)}: {len(rows)} rows, {divergences} divergences')


if __name__ == '__main__':
    main()
