// The frozen `Throwable.printOnDebug` lives in `LogUtils.kt:139` as
//
//     fun Throwable.printOnDebug() {
//         if (BuildConfig.DEBUG) printStackTrace()
//     }
//
// and `BuildConfig` is generated by the Android build, so that file cannot be
// compiled on a desktop JVM. The frozen sources in this harness call the
// extension on their own failure paths, so the harness supplies the release
// behaviour — no output. Nothing the differential contract compares is printed:
// stack traces and debug logs are explicitly not compatibility surfaces.
package io.legado.app.utils

fun Throwable.printOnDebug() {
}
