// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    books,
    groups,
    bookGroups,
    chapters,
    localRoots,
    localFiles,
    textIndex,
    progress,
    replaceRules,
    settings,
    booksNaturalKey,
    booksLocalKey,
    booksShelfOrder,
    groupsName,
    bookGroupsGroup,
    chaptersTocOrder,
    replaceRulesMergeKey,
    replaceRulesOrder,
    localFilesBook,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_source_url)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 books = Shape1(
    source: i0.VersionedTable(
      entityName: 'books',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_3,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 groups = Shape2(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_9,
        _column_1,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 bookGroups = Shape3(
    source: i0.VersionedTable(
      entityName: 'book_groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, group_id)'],
      columns: [_column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 chapters = Shape4(
    source: i0.VersionedTable(
      entityName: 'chapters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, chapter_key)'],
      columns: [
        _column_40,
        _column_42,
        _column_1,
        _column_43,
        _column_44,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localRoots = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_roots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_9, _column_45, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 localFiles = Shape6(
    source: i0.VersionedTable(
      entityName: 'local_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(root_id, relative_path)'],
      columns: [
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_34,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 textIndex = Shape7(
    source: i0.VersionedTable(
      entityName: 'text_index',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(root_id, relative_path, byte_offset)',
        'FOREIGN KEY(root_id, relative_path)REFERENCES local_files(root_id, relative_path)ON DELETE CASCADE',
      ],
      columns: [_column_46, _column_47, _column_52, _column_53, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 progress = Shape8(
    source: i0.VersionedTable(
      entityName: 'progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id)'],
      columns: [
        _column_40,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 replaceRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'replace_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_9,
        _column_1,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(book_id, "key")'],
      columns: [_column_74, _column_75, _column_76, _column_62],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index booksNaturalKey = i1.Index(
    'books_natural_key',
    'CREATE UNIQUE INDEX books_natural_key ON books (source_ref, source_book_url)',
  );
  final i1.Index booksLocalKey = i1.Index(
    'books_local_key',
    'CREATE UNIQUE INDEX books_local_key ON books (root_id, relative_path)',
  );
  final i1.Index booksShelfOrder = i1.Index(
    'books_shelf_order',
    'CREATE INDEX books_shelf_order ON books (shelved, kind, book_order)',
  );
  final i1.Index groupsName = i1.Index(
    'groups_name',
    'CREATE UNIQUE INDEX groups_name ON "groups" (name)',
  );
  final i1.Index bookGroupsGroup = i1.Index(
    'book_groups_group',
    'CREATE INDEX book_groups_group ON book_groups (group_id, book_id)',
  );
  final i1.Index chaptersTocOrder = i1.Index(
    'chapters_toc_order',
    'CREATE INDEX chapters_toc_order ON chapters (book_id, chapter_index)',
  );
  final i1.Index replaceRulesMergeKey = i1.Index(
    'replace_rules_merge_key',
    'CREATE UNIQUE INDEX replace_rules_merge_key ON replace_rules (name, pattern, replacement)',
  );
  final i1.Index replaceRulesOrder = i1.Index(
    'replace_rules_order',
    'CREATE INDEX replace_rules_order ON replace_rules (rule_order)',
  );
  final i1.Index localFilesBook = i1.Index(
    'local_files_book',
    'CREATE INDEX local_files_book ON local_files (book_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get bookSourceUrl =>
      columnsByName['book_source_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupNames =>
      columnsByName['group_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get customOrder =>
      columnsByName['custom_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabledExplore =>
      columnsByName['enabled_explore']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUpdateTime =>
      columnsByName['last_update_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get raw =>
      columnsByName['raw']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'book_source_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_names',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'custom_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled_explore',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (enabled_explore IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_update_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'raw',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceRef =>
      columnsByName['source_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceBookUrl =>
      columnsByName['source_book_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get author =>
      columnsByName['author']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get originName =>
      columnsByName['origin_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get customTag =>
      columnsByName['custom_tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverUrl =>
      columnsByName['cover_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customCoverUrl =>
      columnsByName['custom_cover_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get intro =>
      columnsByName['intro']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customIntro =>
      columnsByName['custom_intro']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get charset =>
      columnsByName['charset']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get latestChapterTitle =>
      columnsByName['latest_chapter_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get latestChapterTime =>
      columnsByName['latest_chapter_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalChapterNum =>
      columnsByName['total_chapter_num']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get canUpdate =>
      columnsByName['can_update']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastCheckTime =>
      columnsByName['last_check_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastCheckCount =>
      columnsByName['last_check_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookOrder =>
      columnsByName['book_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get variable =>
      columnsByName['variable']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get shelved =>
      columnsByName['shelved']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get needsRelink =>
      columnsByName['needs_relink']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get raw =>
      columnsByName['raw']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'network\'',
      defaultValue: const i1.CustomExpression('\'network\''),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_book_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'author',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_cover_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'intro',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_intro',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'charset',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'latest_chapter_title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'latest_chapter_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_chapter_num',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'can_update',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (can_update IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_check_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_check_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'book_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'variable',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'shelved',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (shelved IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'root_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'format',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'needs_relink',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (needs_relink IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cover =>
      columnsByName['cover']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get groupOrder =>
      columnsByName['group_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enableRefresh =>
      columnsByName['enable_refresh']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get show =>
      columnsByName['show']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bookSort =>
      columnsByName['book_sort']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enable_refresh',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enable_refresh IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (show IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'book_sort',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT (-1)',
      defaultValue: const i1.CustomExpression('-1'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'book_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES books(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES "groups"(id)ON DELETE CASCADE',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chapterKey =>
      columnsByName['chapter_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get chapterIndex =>
      columnsByName['chapter_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get variable =>
      columnsByName['variable']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chapter_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get needsRelink =>
      columnsByName['needs_relink']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get format =>
      columnsByName['format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get textLength =>
      columnsByName['text_length']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get needsRelink =>
      columnsByName['needs_relink']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'root_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES local_roots(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'txt\'',
      defaultValue: const i1.CustomExpression('\'txt\''),
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'text_length',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'modified_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'book_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES books(id)ON DELETE SET NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteOffset =>
      columnsByName['byte_offset']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get codeUnitOffset =>
      columnsByName['code_unit_offset']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineIndex =>
      columnsByName['line_index']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_offset',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'code_unit_offset',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'line_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get textOffset =>
      columnsByName['text_offset']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineIndex =>
      columnsByName['line_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offsetInLine =>
      columnsByName['offset_in_line']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get textLength =>
      columnsByName['text_length']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chapterKey =>
      columnsByName['chapter_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get chapterIndex =>
      columnsByName['chapter_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get anchor =>
      columnsByName['anchor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'text_offset',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'line_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offset_in_line',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'text_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chapter_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chapter_index',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'anchor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupName =>
      columnsByName['group_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pattern =>
      columnsByName['pattern']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replacement =>
      columnsByName['replacement']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get excludeScope =>
      columnsByName['exclude_scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scopeTitle =>
      columnsByName['scope_title']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scopeContent =>
      columnsByName['scope_content']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isEnabled =>
      columnsByName['is_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isRegex =>
      columnsByName['is_regex']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeoutMillisecond =>
      columnsByName['timeout_millisecond']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ruleOrder =>
      columnsByName['rule_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get raw =>
      columnsByName['raw']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pattern',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'replacement',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exclude_scope',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scope_title',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (scope_title IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scope_content',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (scope_content IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_regex',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_regex IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'timeout_millisecond',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rule_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get bookId =>
      columnsByName['book_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'book_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
