// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Evaluates every job of one stage against one document.
Future<List<HtmlJobOutcome>> htmlAnalyze(
        {required String html, required List<HtmlRuleJob> jobs}) =>
    LibFjs.instance.api.crateApiHtmlHtmlAnalyze(html: html, jobs: jobs);

/// A rule that could not be evaluated, with the family it belongs to.
class HtmlJobFailure {
  /// `unsupported`, `parse` or `runtime`.
  final String kind;
  final String message;

  const HtmlJobFailure({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HtmlJobFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

class HtmlJobOutcome {
  final String id;

  /// Number of elements an `Elements` job matched.
  final int count;

  /// One value per context element for `Text` jobs.
  final List<String> values;
  final HtmlJobFailure? failure;

  const HtmlJobOutcome({
    required this.id,
    required this.count,
    required this.values,
    this.failure,
  });

  @override
  int get hashCode =>
      id.hashCode ^ count.hashCode ^ values.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HtmlJobOutcome &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          count == other.count &&
          values == other.values &&
          failure == other.failure;
}

/// What one rule job returns.
enum HtmlJobOutput {
  /// Matched elements; only their count leaves the adapter, and later jobs use
  /// them as contexts.
  elements,

  /// One extracted string per context element.
  text,
  ;
}

/// One rule to evaluate against the document.
class HtmlRuleJob {
  /// Caller-chosen id; later jobs reference it as `parent`.
  final String id;

  /// The Book Source rule, with the `@CSS:`/legacy mode prefix, the `@` chain,
  /// the merge operators, the index syntax and the `##` replacement included.
  final String rule;

  /// An earlier `Elements` job id whose matches are this job's contexts.
  /// `None` means the document itself.
  final String? parent;
  final HtmlJobOutput output;

  const HtmlRuleJob({
    required this.id,
    required this.rule,
    this.parent,
    required this.output,
  });

  @override
  int get hashCode =>
      id.hashCode ^ rule.hashCode ^ parent.hashCode ^ output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HtmlRuleJob &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rule == other.rule &&
          parent == other.parent &&
          output == other.output;
}
