// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'text.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `units`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// The defaults the frozen reader starts from: one anchor per 32 KiB, its two
/// enabled default TXT rules, and a 4 MiB scan limit.
TextIndexOptions textDefaultOptions() =>
    LibFjs.instance.api.crateApiTextTextDefaultOptions();

/// Detects a file's encoding.
Future<TextDetection> textDetectEncoding({required String path}) =>
    LibFjs.instance.api.crateApiTextTextDetectEncoding(path: path);

/// Decodes an in-memory byte buffer — an HTTP response body — with a declared
/// encoding name, or with the engine's own detection when the caller has none.
///
/// The Book Source request layer resolves the name first (the frozen
/// `OkHttpUtils.kt:78-96` order: Content-Type charset, else the document's meta
/// charset) and passes `None` only for the frozen `EncodingDetect` fallback.
/// `encoding_rs` decodes GBK, GB18030 and Big5 the same way on all five
/// platforms, which `dart:convert` cannot do at all.
Future<String> textDecodeBytes({required List<int> bytes, String? encoding}) =>
    LibFjs.instance.api
        .crateApiTextTextDecodeBytes(bytes: bytes, encoding: encoding);

/// Encodes text with a declared charset, the request-side half of the same
/// `charset` option: the frozen `URLEncoder.encode(value, charset)` and hutool
/// `queryEncoder.encode(params, charset)` (`AnalyzeUrl.kt:294-334`) percent-escape
/// these bytes. An unknown label is `TextEngineError::UnknownEncoding`, mirroring
/// the `UnsupportedCharsetException` `Charset.forName` throws on the frozen path.
Future<Uint8List> textEncodeBytes(
        {required String text, required String encoding}) =>
    LibFjs.instance.api
        .crateApiTextTextEncodeBytes(text: text, encoding: encoding);

/// Indexes a local file in one pass: encoding, both lengths, anchors, chapters.
Future<TextIndex> textIndexFile(
        {required String path, required TextIndexOptions options}) =>
    LibFjs.instance.api.crateApiTextTextIndexFile(path: path, options: options);

/// Reads a bounded window of a local file.
Future<TextWindow> textReadWindow({required TextWindowRequest request}) =>
    LibFjs.instance.api.crateApiTextTextReadWindow(request: request);

/// Converts Chinese text with the tables ADR 0010 records.
///
/// Synchronous because the frozen `java.t2s`/`java.s2t` are: a rule calls them
/// inside a script and uses the result immediately.
String textConvert({required String text, required TextDirection direction}) =>
    LibFjs.instance.api
        .crateApiTextTextConvert(text: text, direction: direction);

/// One sparse anchor: a line start in bytes, in code units, and in lines. These
/// are the `text_index` rows.
class TextAnchor {
  /// Byte offset in the file.
  final PlatformInt64 byteOffset;

  /// UTF-16 code-unit offset in the decoded text.
  final PlatformInt64 codeUnitOffset;

  /// Zero-based line index.
  final PlatformInt64 lineIndex;

  const TextAnchor({
    required this.byteOffset,
    required this.codeUnitOffset,
    required this.lineIndex,
  });

  @override
  int get hashCode =>
      byteOffset.hashCode ^ codeUnitOffset.hashCode ^ lineIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextAnchor &&
          runtimeType == other.runtimeType &&
          byteOffset == other.byteOffset &&
          codeUnitOffset == other.codeUnitOffset &&
          lineIndex == other.lineIndex;
}

/// One chapter boundary, as the TOC rules found it.
class TextChapter {
  /// The matched text, without the whitespace a rule's lookbehind excludes.
  final String title;

  /// Byte offset of the chapter's line start.
  final PlatformInt64 byteOffset;

  /// Code-unit offset of the same position.
  final PlatformInt64 codeUnitOffset;

  /// Zero-based line index of the same position.
  final PlatformInt64 lineIndex;

  const TextChapter({
    required this.title,
    required this.byteOffset,
    required this.codeUnitOffset,
    required this.lineIndex,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      byteOffset.hashCode ^
      codeUnitOffset.hashCode ^
      lineIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextChapter &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          byteOffset == other.byteOffset &&
          codeUnitOffset == other.codeUnitOffset &&
          lineIndex == other.lineIndex;
}

/// Encoding detection's answer for one file.
class TextDetection {
  /// The Encoding Standard name (`UTF-8`, `GBK`, `Big5`, …).
  final String encoding;

  /// Whether the name came from a byte order mark.
  final bool bom;

  const TextDetection({
    required this.encoding,
    required this.bom,
  });

  @override
  int get hashCode => encoding.hashCode ^ bom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextDetection &&
          runtimeType == other.runtimeType &&
          encoding == other.encoding &&
          bom == other.bom;
}

/// Which way to convert.
enum TextDirection {
  /// `java.t2s`, the reader's 简体 setting.
  traditionalToSimplified,

  /// `java.s2t`, the reader's 繁體 setting.
  simplifiedToTraditional,
  ;
}

@freezed
sealed class TextEngineError with _$TextEngineError implements FrbException {
  const TextEngineError._();

  /// The file could not be read.
  const factory TextEngineError.io(
    String field0,
  ) = TextEngineError_Io;

  /// The encoding name is not one the Encoding Standard knows.
  const factory TextEngineError.unknownEncoding(
    String field0,
  ) = TextEngineError_UnknownEncoding;

  /// The file's byte order mark names an encoding the engine does not decode.
  const factory TextEngineError.unsupportedEncoding(
    String field0,
  ) = TextEngineError_UnsupportedEncoding;

  /// The anchors handed in are stale: the scan from the anchor passed the
  /// caller's limit.
  const factory TextEngineError.anchorTooFar({
    /// Bytes scanned before giving up.
    required PlatformInt64 scannedBytes,

    /// The caller's limit.
    required PlatformInt64 limit,
  }) = TextEngineError_AnchorTooFar;

  /// The requested offset is past the end of the file.
  const factory TextEngineError.offsetOutOfRange({
    /// The requested code-unit offset.
    required PlatformInt64 offset,

    /// The file's code-unit length.
    required PlatformInt64 codeUnitLength,
  }) = TextEngineError_OffsetOutOfRange;
}

/// One pass over a local file.
class TextIndex {
  /// The detected encoding's name.
  final String encoding;

  /// The file's size in bytes.
  final PlatformInt64 byteLength;

  /// The file's length in UTF-16 code units.
  final PlatformInt64 codeUnitLength;

  /// Line starts, sparse by the anchor stride.
  final List<TextAnchor> anchors;

  /// Chapter boundaries, empty when no rule matched.
  final List<TextChapter> chapters;

  /// Rules that do not compile. The frozen reader ignores them and opens the
  /// book without them.
  final List<String> ignoredRules;

  const TextIndex({
    required this.encoding,
    required this.byteLength,
    required this.codeUnitLength,
    required this.anchors,
    required this.chapters,
    required this.ignoredRules,
  });

  @override
  int get hashCode =>
      encoding.hashCode ^
      byteLength.hashCode ^
      codeUnitLength.hashCode ^
      anchors.hashCode ^
      chapters.hashCode ^
      ignoredRules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextIndex &&
          runtimeType == other.runtimeType &&
          encoding == other.encoding &&
          byteLength == other.byteLength &&
          codeUnitLength == other.codeUnitLength &&
          anchors == other.anchors &&
          chapters == other.chapters &&
          ignoredRules == other.ignoredRules;
}

/// How to index a file.
class TextIndexOptions {
  /// One anchor at least every this many bytes, aligned to a line start.
  final PlatformInt64 anchorStrideBytes;

  /// TOC rules in the frozen reader's order. Empty means no chapter
  /// detection.
  final List<String> tocRules;

  /// The longest anchor-to-target scan a window read may perform.
  final PlatformInt64 maxScanBytes;

  const TextIndexOptions({
    required this.anchorStrideBytes,
    required this.tocRules,
    required this.maxScanBytes,
  });

  @override
  int get hashCode =>
      anchorStrideBytes.hashCode ^ tocRules.hashCode ^ maxScanBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextIndexOptions &&
          runtimeType == other.runtimeType &&
          anchorStrideBytes == other.anchorStrideBytes &&
          tocRules == other.tocRules &&
          maxScanBytes == other.maxScanBytes;
}

/// A bounded read's answer.
class TextWindow {
  /// The decoded text.
  final String text;

  /// The code-unit offset the window starts at.
  final PlatformInt64 codeUnitOffset;

  /// The byte offset the window starts at.
  final PlatformInt64 byteOffset;

  /// The line the window starts in.
  final PlatformInt64 lineIndex;

  /// Whether the window ends at the end of the file.
  final bool atEnd;

  const TextWindow({
    required this.text,
    required this.codeUnitOffset,
    required this.byteOffset,
    required this.lineIndex,
    required this.atEnd,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      codeUnitOffset.hashCode ^
      byteOffset.hashCode ^
      lineIndex.hashCode ^
      atEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextWindow &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          codeUnitOffset == other.codeUnitOffset &&
          byteOffset == other.byteOffset &&
          lineIndex == other.lineIndex &&
          atEnd == other.atEnd;
}

/// A window read request.
class TextWindowRequest {
  /// The file to read.
  final String path;

  /// The encoding name from the index that produced the anchor.
  final String encoding;

  /// The nearest anchor the caller has stored, if any.
  final TextAnchor? anchor;

  /// The code-unit offset the window starts at.
  final PlatformInt64 codeUnitOffset;

  /// How many code units at most.
  final PlatformInt64 maxCodeUnits;

  /// The longest scan from the anchor before the read reports stale anchors.
  final PlatformInt64 maxScanBytes;

  const TextWindowRequest({
    required this.path,
    required this.encoding,
    this.anchor,
    required this.codeUnitOffset,
    required this.maxCodeUnits,
    required this.maxScanBytes,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      encoding.hashCode ^
      anchor.hashCode ^
      codeUnitOffset.hashCode ^
      maxCodeUnits.hashCode ^
      maxScanBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextWindowRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          encoding == other.encoding &&
          anchor == other.anchor &&
          codeUnitOffset == other.codeUnitOffset &&
          maxCodeUnits == other.maxCodeUnits &&
          maxScanBytes == other.maxScanBytes;
}
